### PR TITLE
Add IPR reqired files

### LINKED ISSUE #53: Add IPR manager required files
Before import repository in the [IPR manager](https://labs.w3.org/repo-manager/repo/import) tool, we need to add the below files:

- [x]  Add CONTRIBUTING.md
- [x]  Add w3c.json
- [x]  Add an index.html that's a bare-bones ReSpec spec ready to be edited.
- [x]  Add CODE_OF_CONDUCT.md.

Related  immersive-web/administrivia#102

### PR DESCRIPTION
**Pull request by Yonet**
Closes #53

### CODE REVIEW

**Comment by himorin** [comment]
please use w3cid '87846' for immersive-web CG

**Comment by Yonet** [comment]
@himorin changed the id, thank you for catching that.

**Comment by himorin** [comment]
(need to be confirmed by @dontcallmedom , but I wonder whether cg-report or rec-track is appreciate for repo-type...)

**Review by himorin — APPROVED** [review]

**Comment by dontcallmedom** [comment]
If indeed this is still for the CG (rather than the WG), then it should be "cg-report" rather than "rec-track".

(Note that the IPR tool will add the said files (w3c.json et al) when importing the repo if asked to.)

**Pull request closed without merging**
